on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies with yarn
        uses: borales/actions-yarn@v4
        run: yarn

      - name: Run tests
        uses: borales/actions-yarn@v4
        run: yarn test